"""Regenerate the install cell in notebooks/gpt-dev-flowscope.ipynb from src/flowscope.

Colab can't pip-install this repo, so the cell writes the package files next to the notebook.
Run after changing anything in src/flowscope:  uv run python scripts/build_notebook.py
"""
import json, pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
NB = ROOT / "notebooks" / "gpt-dev-flowscope.ipynb"
PKG = ROOT / "src" / "flowscope"
FILES = ["__init__.py", "scope.py", "server.py", "tour.py", "tour.js"]


def install_cell_source():
    files = {f"flowscope/{name}": (PKG / name).read_text() for name in FILES}
    return ("# Writes the flowscope package next to this notebook (generated by scripts/build_notebook.py)\n"
            "import os, sys, importlib\n"
            f"files = {json.dumps(files, indent=0)}\n"
            "for path, src in files.items():\n"
            "    os.makedirs(os.path.dirname(path), exist_ok=True)\n"
            "    with open(path, 'w') as f:\n"
            "        f.write(src)\n"
            "for m in [m for m in sys.modules if m == 'flowscope' or m.startswith('flowscope.')]:\n"
            "    del sys.modules[m]  # pick up the new files on re-run\n"
            "print('flowscope written:', ', '.join(files))\n")


def main():
    nb = json.loads(NB.read_text())
    cell = next(c for c in nb["cells"] if c["metadata"].get("id") == "fsWrite01")
    cell["source"] = install_cell_source().splitlines(True)
    cell["outputs"], cell["execution_count"] = [], None
    NB.write_text(json.dumps(nb, indent=1))
    print(f"updated {NB.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
